services:
  - type: web
    name: nirmaan-setu
    runtime: static
    plan: free
    buildCommand: echo "static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /
        destination: /index.html
